spring.application.name=community
spring.datasource.url=jdbc:h2:file:${H2_DB_PATH:~/test}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
